---
title: "Reproducible Research Assignment for Github"
author: "1056495"
date: "2022-12-05"
output: html_document
---
```{r set up}
#setwd("~/Penguin_Project") 

source("Penguin_Libraries.R") #includes all of the packages that is used for the code.
source("functions/Plotting.R")
source("functions/cleaning.R")


raw_penguin <- write.csv(penguins_raw, "raw_data/penguins_raw.csv") 
penguins_Raw <- read.csv("raw_data/penguins_raw.csv", na = c(" ","NA","N/A")) #load the data
penguins_clean <- cleaning(penguins_Raw)
write.csv(penguins_clean, "clean_data/penguins_clean.csv")

penguins_flippers <- remove_empty_flipper_length(penguins_clean)
#removed nas of flipper length data

culmen_l_flipper_na <- remove_empty_culmen_length(penguins_flippers)

#dataset now called culmen_l_flipper_na has nas removed of flipper lenghth (penguin_flipper) and culmen length
```

```{r functions I use}
cleaning <- function(data_raw){
  data_raw %>%
    clean_names() %>%
    remove_empty(c("rows", "cols")) %>%
    select(-starts_with("delta")) %>%
    select(-comments)
}

remove_empty_flipper_length <- function(data_clean){
  data_clean %>%
    filter(!is.na(flipper_length_mm)) %>%
    select(species, flipper_length_mm, culmen_length_mm, island, sex)
}
remove_empty_culmen_length <- function(data_clean){
  data_clean %>%
    filter(!is.na(culmen_length_mm)) %>%
    select(species, flipper_length_mm, culmen_length_mm, island, sex)
}

lr_location_plot <- function (culmen_l_flipper_na){
  culmen_l_flipper_na %>%
    ggplot(aes(y = flipper_length_mm, x = culmen_length_mm, colour = island)) + 
    geom_point(show.legend = TRUE, size = 1.4, alpha = 0.7)+
    labs(title = "The correlation between flipper length and culmen length", 
         subtitle = "The correlation of flipper length and culmen length according to the species and the island",
         x = "Culmen length (mm)", y = "Flipper length (mm)",
         colour = "Island")+
    theme_bw()+
    scale_colour_manual(values = c("Biscoe" = "#45B5A8",
                                   "Dream"= "#002147",
                                   "Torgersen" = "#E2679F"))+
    facet_wrap(~species)+
    geom_smooth(aes(x = culmen_length_mm, y = flipper_length_mm), 
                method = "lm", se = FALSE, inherit.aes = FALSE)
}

save_location_plot_png <- function(culmen_l_flipper_na, 
                                  filename, size, res, scaling){
  agg_png(filename, width   =  size, 
          height  =  size, 
          units   =  "cm", 
          res     =  res, 
          scaling =  scaling)
  location_plot <- lr_location_plot(culmen_l_flipper_na)
  print(location_plot)
  dev.off()
}

```


#Question 04: Run a statistical test on the Palmer Penguins dataset and produce a figure to explain it.

```{r  checking for normality echo = FALSE, message = FALSE, warning = FALSE, results = 'hide'}
hist(culmen_l_flipper_na$culmen_length_mm)
qqnorm(culmen_l_flipper_na$culmen_length_mm)
qqline(culmen_l_flipper_na$culmen_length_mm)
hist(culmen_l_flipper_na$flipper_length_mm)
qqnorm(culmen_l_flipper_na$flipper_length_mm)
qqline(culmen_l_flipper_na$flipper_length_mm)
```

```{r Spearman's Rank echo = FALSE, message = FALSE, warning = FALSE, results = 'hide'}
cor.test(culmen_l_flipper_na$culmen_length_mm, culmen_l_flipper_na$flipper_length_mm, method = "spearman")

by_Adelie <- filter(culmen_l_flipper_na, species == "Adelie Penguin (Pygoscelis adeliae)")
by_Chinstrap <- filter(culmen_l_flipper_na, species == "Chinstrap penguin (Pygoscelis antarctica)")
by_Gentoo <- filter(culmen_l_flipper_na, species == "Gentoo penguin (Pygoscelis papua)")

cor.test(by_Adelie$culmen_length_mm, by_Adelie$flipper_length_mm, method = "spearman")
cor.test(by_Chinstrap$culmen_length_mm, by_Chinstrap$flipper_length_mm, method = "spearman")
cor.test(by_Gentoo$culmen_length_mm, by_Gentoo$flipper_length_mm, method = "spearman")
```


```{r linear regression echo = FALSE, message = FALSE, warning = FALSE, results = 'hide'}
culmen_flipper_mod <- lm(flipper_length_mm ~ culmen_length_mm, culmen_l_flipper_na)
summary(culmen_flipper_mod)
lm(flipper_length_mm ~ culmen_length_mm, by_Adelie)
lm(flipper_length_mm ~ culmen_length_mm, by_Chinstrap)
lm(flipper_length_mm ~ culmen_length_mm, by_Gentoo)

lr_location_plot(culmen_l_flipper_na)
save_location_plot_png(culmen_l_flipper_na, 
                      "figures/fig02_report.png", 
                      size = 15, res = 600, scaling=0.8)
```

